import {
  User,
  Customer,
  Vehicle,
  Booking,
  JobCard,
  Part,
  Labour,
  Invoice,
  Payment,
  ServiceHistoryItem,
  Notification,
  AuditLog,
} from '@/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin',
    name: 'Rahul Khurana',
    email: 'admin@autocare360.demo',
    role: 'ADMIN',
    phone: '+91 98200 00001',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'user-advisor',
    name: 'Sameer Joshi',
    email: 'advisor@autocare360.demo',
    role: 'SERVICE_ADVISOR',
    phone: '+91 98200 00002',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'user-manager',
    name: 'Arvind Swamy',
    email: 'manager@autocare360.demo',
    role: 'SERVICE_MANAGER',
    phone: '+91 98200 00003',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'user-technician',
    name: 'Deepak Shinde',
    email: 'technician@autocare360.demo',
    role: 'TECHNICIAN',
    phone: '+91 98200 00004',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'user-billing',
    name: 'Neha Kulkarni',
    email: 'billing@autocare360.demo',
    role: 'BILLING_STAFF',
    phone: '+91 98200 00005',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'user-customer',
    name: 'Rahul Patil',
    email: 'customer@autocare360.demo',
    role: 'CUSTOMER',
    phone: '+91 98201 12345',
    customerId: 'cust-1',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=256',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Rahul Patil',
    phone: '+91 98201 12345',
    email: 'customer@autocare360.demo',
    address: 'Flat 402, Shivam Apts, Baner, Pune, MH',
    city: 'Pune',
    notes: 'Premium customer, prefers synthetic engine oil and WhatsApp alerts',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-09-15T11:00:00Z',
  },
  {
    id: 'cust-2',
    name: 'Priya Sharma',
    phone: '+91 98112 54321',
    email: 'priya.sharma@example.in',
    address: 'B-12, Greater Kailash 1, New Delhi, DL',
    city: 'New Delhi',
    notes: 'Requested doorstep pickup and drop',
    createdAt: '2026-02-14T09:30:00Z',
    updatedAt: '2026-09-18T14:20:00Z',
  },
  {
    id: 'cust-3',
    name: 'Amit Verma',
    phone: '+91 98450 67890',
    email: 'amit.verma@example.in',
    address: '304, Green Glen Layout, Bellandur, Bengaluru, KA',
    city: 'Bengaluru',
    notes: 'Wants detailed wheel alignment report',
    createdAt: '2026-03-05T12:00:00Z',
    updatedAt: '2026-09-20T10:15:00Z',
  },
  {
    id: 'cust-4',
    name: 'Vikram Malhotra',
    phone: '+91 98210 99887',
    email: 'vikram.malhotra@example.in',
    address: '14A, Silver Beach Estate, Juhu, Mumbai, MH',
    city: 'Mumbai',
    notes: 'Hybrid powertrain inspection mandatory',
    createdAt: '2026-03-22T15:00:00Z',
    updatedAt: '2026-09-21T16:00:00Z',
  },
  {
    id: 'cust-5',
    name: 'Sunita Desai',
    phone: '+91 98790 11223',
    email: 'sunita.desai@example.in',
    address: 'Plot 88, Bodakdev, Ahmedabad, GJ',
    city: 'Ahmedabad',
    notes: 'Senior citizen discount eligible',
    createdAt: '2026-04-10T11:00:00Z',
    updatedAt: '2026-09-22T09:00:00Z',
  },
  {
    id: 'cust-6',
    name: 'Rajesh Iyer',
    phone: '+91 98401 44556',
    email: 'rajesh.iyer@example.in',
    address: '42, Besant Nagar 4th Avenue, Chennai, TN',
    city: 'Chennai',
    notes: 'AC cooling efficiency check requested',
    createdAt: '2026-05-15T08:30:00Z',
    updatedAt: '2026-09-23T11:45:00Z',
  },
  {
    id: 'cust-7',
    name: 'Sneha Reddy',
    phone: '+91 98850 77889',
    email: 'sneha.reddy@example.in',
    address: 'Road No 12, Banjara Hills, Hyderabad, TS',
    city: 'Hyderabad',
    notes: 'Brake pedal spongy feeling reported',
    createdAt: '2026-06-01T10:15:00Z',
    updatedAt: '2026-09-23T15:30:00Z',
  },
  {
    id: 'cust-8',
    name: 'Arjun Nair',
    phone: '+91 98470 33221',
    email: 'arjun.nair@example.in',
    address: 'Panampilly Nagar, Kochi, KL',
    city: 'Kochi',
    notes: 'Pre-monsoon safety inspection',
    createdAt: '2026-06-20T14:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'cust-9',
    name: 'Meera Joshi',
    phone: '+91 98220 55667',
    email: 'meera.joshi@example.in',
    address: 'Model Colony, Shivajinagar, Pune, MH',
    city: 'Pune',
    notes: 'Off-road suspension inspection',
    createdAt: '2026-07-08T16:20:00Z',
    updatedAt: '2026-09-20T12:00:00Z',
  },
  {
    id: 'cust-10',
    name: 'Rohan Gupta',
    phone: '+91 98100 22334',
    email: 'rohan.gupta@example.in',
    address: 'DLF Phase 5, Golf Course Road, Gurgaon, HR',
    city: 'Gurgaon',
    notes: 'Turbo whistle noise investigation',
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-09-22T17:00:00Z',
  },
  {
    id: 'cust-11',
    name: 'Deepa Krishnan',
    phone: '+91 98412 88990',
    email: 'deepa.k@example.in',
    address: 'Anna Nagar West, Chennai, TN',
    city: 'Chennai',
    notes: 'Regular periodic maintenance',
    createdAt: '2026-08-15T11:00:00Z',
    updatedAt: '2026-09-23T10:00:00Z',
  },
  {
    id: 'cust-12',
    name: 'Kunal Singhal',
    phone: '+91 98188 66778',
    email: 'kunal.s@example.in',
    address: 'Sector 50, Noida, UP',
    city: 'Noida',
    notes: 'Infotainment software update required',
    createdAt: '2026-09-01T09:00:00Z',
    updatedAt: '2026-09-24T08:15:00Z',
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    customerId: 'cust-1',
    registrationNumber: 'MH 12 AB 4587',
    vin: 'MAT623490N1K98201',
    make: 'Tata',
    model: 'Nexon',
    variant: 'XZ+ (O) Dark Edition',
    manufacturingYear: 2022,
    fuelType: 'DIESEL',
    currentOdometer: 34500,
    color: 'Atlas Black',
    customerName: 'Rahul Patil',
    createdAt: '2026-01-10T10:05:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-2',
    customerId: 'cust-2',
    registrationNumber: 'DL 03 CC 9821',
    vin: 'MALH34125M8K54321',
    make: 'Hyundai',
    model: 'Creta',
    variant: 'SX (O) 1.5 IVT',
    manufacturingYear: 2021,
    fuelType: 'PETROL',
    currentOdometer: 42100,
    color: 'Polar White',
    customerName: 'Priya Sharma',
    createdAt: '2026-02-14T09:35:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-3',
    customerId: 'cust-3',
    registrationNumber: 'KA 05 MN 3344',
    vin: 'MA1TA2WJK81967890',
    make: 'Mahindra',
    model: 'XUV700',
    variant: 'AX7 Luxury AWD',
    manufacturingYear: 2023,
    fuelType: 'DIESEL',
    currentOdometer: 21800,
    color: 'Midnight Black',
    customerName: 'Amit Verma',
    createdAt: '2026-03-05T12:05:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-4',
    customerId: 'cust-4',
    registrationNumber: 'MH 02 EF 1209',
    vin: 'MBJ11B86K00998871',
    make: 'Toyota',
    model: 'Innova Hycross',
    variant: 'ZX(O) Strong Hybrid',
    manufacturingYear: 2023,
    fuelType: 'HYBRID',
    currentOdometer: 28400,
    color: 'Attitude Black Mica',
    customerName: 'Vikram Malhotra',
    createdAt: '2026-03-22T15:05:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-5',
    customerId: 'cust-5',
    registrationNumber: 'GJ 01 KK 7712',
    vin: 'MA3FNE81S00112234',
    make: 'Maruti Suzuki',
    model: 'Grand Vitara',
    variant: 'Alpha AllGrip 1.5L',
    manufacturingYear: 2022,
    fuelType: 'PETROL',
    currentOdometer: 38900,
    color: 'Nexa Blue',
    customerName: 'Sunita Desai',
    createdAt: '2026-04-10T11:05:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-6',
    customerId: 'cust-6',
    registrationNumber: 'TN 07 AX 6543',
    vin: 'MZBH451CLP4455612',
    make: 'Kia',
    model: 'Seltos',
    variant: 'GTX Plus 1.5 Turbo DCT',
    manufacturingYear: 2021,
    fuelType: 'PETROL',
    currentOdometer: 49500,
    color: 'Gravity Grey',
    customerName: 'Rajesh Iyer',
    createdAt: '2026-05-15T08:35:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-7',
    customerId: 'cust-7',
    registrationNumber: 'TS 09 CD 4321',
    vin: 'MAKGM6650L7788910',
    make: 'Honda',
    model: 'City',
    variant: 'ZX CVT Petrol',
    manufacturingYear: 2020,
    fuelType: 'PETROL',
    currentOdometer: 58200,
    color: 'Golden Brown Metallic',
    customerName: 'Sneha Reddy',
    createdAt: '2026-06-01T10:20:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-8',
    customerId: 'cust-8',
    registrationNumber: 'KL 07 BG 8899',
    vin: 'MAT623490R1332219',
    make: 'Tata',
    model: 'Harrier',
    variant: 'Fearless Plus AT',
    manufacturingYear: 2023,
    fuelType: 'DIESEL',
    currentOdometer: 16500,
    color: 'Sunlit Yellow',
    customerName: 'Arjun Nair',
    createdAt: '2026-06-20T14:05:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-9',
    customerId: 'cust-9',
    registrationNumber: 'MH 14 GH 5678',
    vin: 'MA1TA2WJK81556671',
    make: 'Mahindra',
    model: 'Thar',
    variant: 'LX 4x4 Hard Top Diesel',
    manufacturingYear: 2022,
    fuelType: 'DIESEL',
    currentOdometer: 31200,
    color: 'Red Rage',
    customerName: 'Meera Joshi',
    createdAt: '2026-07-08T16:25:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-10',
    customerId: 'cust-10',
    registrationNumber: 'HR 26 BX 9012',
    vin: 'TMBNA7NW9N0223341',
    make: 'Skoda',
    model: 'Kushaq',
    variant: 'Style 1.5 TSI DSG',
    manufacturingYear: 2022,
    fuelType: 'PETROL',
    currentOdometer: 36700,
    color: 'Honey Orange',
    customerName: 'Rohan Gupta',
    createdAt: '2026-08-01T10:05:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-11',
    customerId: 'cust-11',
    registrationNumber: 'TN 09 BZ 1122',
    vin: 'WVWZZZ6RZNY889901',
    make: 'Volkswagen',
    model: 'Taigun',
    variant: 'GT Plus 1.5 TSI DSG',
    manufacturingYear: 2023,
    fuelType: 'PETROL',
    currentOdometer: 19400,
    color: 'Wild Cherry Red',
    customerName: 'Deepa Krishnan',
    createdAt: '2026-08-15T11:05:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-12',
    customerId: 'cust-12',
    registrationNumber: 'UP 16 CZ 7654',
    vin: 'SAJWA02D3M7667789',
    make: 'MG',
    model: 'Hector',
    variant: 'Sharp Pro 2.0 Diesel 6MT',
    manufacturingYear: 2021,
    fuelType: 'DIESEL',
    currentOdometer: 51200,
    color: 'Havana Grey',
    customerName: 'Kunal Singhal',
    createdAt: '2026-09-01T09:05:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-13',
    customerId: 'cust-1',
    registrationNumber: 'MH 12 XY 9900',
    vin: 'MALH34125M8K99001',
    make: 'Tata',
    model: 'Tiago EV',
    variant: 'XZ+ Tech Lux 24kWh',
    manufacturingYear: 2023,
    fuelType: 'ELECTRIC',
    currentOdometer: 14200,
    color: 'Teal Blue',
    customerName: 'Rahul Patil',
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-14',
    customerId: 'cust-4',
    registrationNumber: 'MH 02 AA 8899',
    vin: 'MBJ11B86K00889922',
    make: 'Toyota',
    model: 'Fortuner',
    variant: '4x4 AT Diesel',
    manufacturingYear: 2021,
    fuelType: 'DIESEL',
    currentOdometer: 64000,
    color: 'Super White',
    customerName: 'Vikram Malhotra',
    createdAt: '2026-04-01T10:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'veh-15',
    customerId: 'cust-3',
    registrationNumber: 'KA 03 EQ 4545',
    vin: 'MA3FNE81S00454511',
    make: 'Maruti Suzuki',
    model: 'Baleno',
    variant: 'Alpha 1.2 Petrol AMT',
    manufacturingYear: 2022,
    fuelType: 'PETROL',
    currentOdometer: 29800,
    color: 'Luxe Beige',
    customerName: 'Amit Verma',
    createdAt: '2026-04-15T11:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
];

export const INITIAL_PARTS: Part[] = [
  {
    id: 'part-1',
    partNumber: 'OIL-SYN-5W30',
    name: 'Castrol Edge Fully Synthetic 5W-30 (3.5L)',
    category: 'Fluids & Lubricants',
    brand: 'Castrol',
    unitPrice: 2450,
    stockQuantity: 42,
    reorderLevel: 10,
    supplier: 'Castrol India Ltd',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-2',
    partNumber: 'FLT-OIL-BSH',
    name: 'Bosch High Efficiency Spin-On Oil Filter',
    category: 'Filters',
    brand: 'Bosch OEM',
    unitPrice: 380,
    stockQuantity: 28,
    reorderLevel: 12,
    supplier: 'Bosch Automotive Aftermarket',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-3',
    partNumber: 'FLT-AIR-PUR',
    name: 'Purolator Engine Air Filter Element',
    category: 'Filters',
    brand: 'Purolator',
    unitPrice: 520,
    stockQuantity: 24,
    reorderLevel: 8,
    supplier: 'Mahle Anand Thermal Systems',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-4',
    partNumber: 'FLT-AC-VAL',
    name: 'Valeo Activated Carbon Cabin AC Filter',
    category: 'Filters',
    brand: 'Valeo',
    unitPrice: 650,
    stockQuantity: 18,
    reorderLevel: 6,
    supplier: 'Valeo India Pvt Ltd',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-5',
    partNumber: 'BRK-PAD-FRT',
    name: 'Brembo Low-Metallic Front Brake Pads Set',
    category: 'Braking',
    brand: 'Brembo Ceramic',
    unitPrice: 2800,
    stockQuantity: 3,
    reorderLevel: 6,
    supplier: 'Brembo Brake Systems India',
    taxRate: 18,
    status: 'LOW_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-6',
    partNumber: 'BRK-SHOE-RR',
    name: 'TVS Girling Rear Drum Brake Shoe Set',
    category: 'Braking',
    brand: 'TVS Girling',
    unitPrice: 1450,
    stockQuantity: 14,
    reorderLevel: 5,
    supplier: 'Brakes India Pvt Ltd',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-7',
    partNumber: 'BRK-DISC-280',
    name: 'Front Ventilated Brake Rotor Disc 280mm Pair',
    category: 'Braking',
    brand: 'Brembo OEM',
    unitPrice: 4200,
    stockQuantity: 8,
    reorderLevel: 4,
    supplier: 'Brembo Brake Systems India',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-8',
    partNumber: 'FLD-DOT4-500',
    name: 'Castrol Response Super DOT 4 Brake Fluid (500ml)',
    category: 'Fluids & Lubricants',
    brand: 'Castrol',
    unitPrice: 340,
    stockQuantity: 26,
    reorderLevel: 10,
    supplier: 'Castrol India Ltd',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-9',
    partNumber: 'COOL-SHL-3L',
    name: 'Shell GlycoCool Premix Long Life Coolant 3L',
    category: 'Fluids & Lubricants',
    brand: 'Shell',
    unitPrice: 850,
    stockQuantity: 16,
    reorderLevel: 6,
    supplier: 'Shell Lubricants India',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-10',
    partNumber: 'SPK-NGK-IR4',
    name: 'NGK Laser Iridium Spark Plugs (Pack of 4)',
    category: 'Ignition & Electrical',
    brand: 'NGK Spark Plugs',
    unitPrice: 1950,
    stockQuantity: 12,
    reorderLevel: 5,
    supplier: 'NGK Spark Plugs India',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-11',
    partNumber: 'FLT-FUEL-MHL',
    name: 'Mahle In-Line Diesel Fuel Filter Assembly',
    category: 'Filters',
    brand: 'Mahle',
    unitPrice: 920,
    stockQuantity: 9,
    reorderLevel: 4,
    supplier: 'Mahle Filter Systems',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-12',
    partNumber: 'WIP-BSH-AERO',
    name: 'Bosch Clear Advantage Frameless Wipers (24"+16")',
    category: 'Wiper & Washers',
    brand: 'Bosch',
    unitPrice: 1150,
    stockQuantity: 17,
    reorderLevel: 6,
    supplier: 'Bosch Automotive Aftermarket',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-13',
    partNumber: 'BAT-EXD-65AH',
    name: 'Exide Mileage Maintenance Free 12V 65Ah Battery',
    category: 'Ignition & Electrical',
    brand: 'Exide',
    unitPrice: 6200,
    stockQuantity: 7,
    reorderLevel: 3,
    supplier: 'Exide Industries Ltd',
    taxRate: 28,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-14',
    partNumber: 'BLT-GAT-6PK',
    name: 'Gates Micro-V Auxiliary Serpentine Drive Belt',
    category: 'Engine Components',
    brand: 'Gates',
    unitPrice: 780,
    stockQuantity: 11,
    reorderLevel: 4,
    supplier: 'Gates India Pvt Ltd',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-15',
    partNumber: 'SUS-BSH-MNR',
    name: 'Monroe Heavy-Duty Front Suspension Bush Kit',
    category: 'Suspension & Steering',
    brand: 'Monroe',
    unitPrice: 1850,
    stockQuantity: 2,
    reorderLevel: 5,
    supplier: 'Tenneco Automotive India',
    taxRate: 18,
    status: 'LOW_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-16',
    partNumber: 'FLD-ATF-MTL',
    name: 'Motul Multi ATF 100% Synthetic Transmission Fluid 4L',
    category: 'Fluids & Lubricants',
    brand: 'Motul',
    unitPrice: 3200,
    stockQuantity: 10,
    reorderLevel: 3,
    supplier: 'Atlantic Lubricants & Specialities',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-17',
    partNumber: 'LGT-PHL-H4',
    name: 'Philips X-tremeVision Pro150 H4 Headlight Bulb (Pair)',
    category: 'Lighting',
    brand: 'Philips',
    unitPrice: 1250,
    stockQuantity: 15,
    reorderLevel: 5,
    supplier: 'Lumileds India',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-18',
    partNumber: 'HRN-HLA-TWN',
    name: 'Hella Black Twin Tone Trumpet Horn Set 12V',
    category: 'Accessories & Horns',
    brand: 'Hella',
    unitPrice: 1350,
    stockQuantity: 8,
    reorderLevel: 3,
    supplier: 'Hella India Lighting Ltd',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-19',
    partNumber: 'GAS-R134A-450',
    name: 'Floron Refrigerant Gas R134a Canister 450g',
    category: 'Air Conditioning',
    brand: 'Floron',
    unitPrice: 750,
    stockQuantity: 22,
    reorderLevel: 8,
    supplier: 'SRF Limited',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-20',
    partNumber: 'SHK-MNR-FRT',
    name: 'Monroe Gas-Magnum Front Strut Damper Assembly',
    category: 'Suspension & Steering',
    brand: 'Monroe',
    unitPrice: 3800,
    stockQuantity: 6,
    reorderLevel: 3,
    supplier: 'Tenneco Automotive India',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-21',
    partNumber: 'STEER-TIE-RN',
    name: 'Rane TRW Outer Tie Rod End (Steering)',
    category: 'Suspension & Steering',
    brand: 'Rane TRW',
    unitPrice: 950,
    stockQuantity: 1,
    reorderLevel: 4,
    supplier: 'Rane TRW Steering Systems Ltd',
    taxRate: 18,
    status: 'LOW_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-22',
    partNumber: 'CLT-VAL-SET',
    name: 'Valeo Clutch Plate & Pressure Plate Assembly',
    category: 'Transmission & Clutch',
    brand: 'Valeo OEM',
    unitPrice: 5600,
    stockQuantity: 4,
    reorderLevel: 2,
    supplier: 'Valeo India Pvt Ltd',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-23',
    partNumber: 'WSH-CONC-1L',
    name: 'Sonax Clear Glass Concentrated Windshield Washer (1L)',
    category: 'Fluids & Lubricants',
    brand: 'Sonax',
    unitPrice: 280,
    stockQuantity: 35,
    reorderLevel: 10,
    supplier: 'Sonax Car Care India',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-24',
    partNumber: 'OIL-GEAR-80W90',
    name: 'Servo Gear Super 80W-90 Extreme Pressure Oil (2L)',
    category: 'Fluids & Lubricants',
    brand: 'Indian Oil Servo',
    unitPrice: 720,
    stockQuantity: 18,
    reorderLevel: 6,
    supplier: 'Indian Oil Corporation',
    taxRate: 18,
    status: 'IN_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'part-25',
    partNumber: 'BRK-CALIPER-PIN',
    name: 'Brake Caliper Guide Pin & Boot Kit',
    category: 'Braking',
    brand: 'KBX',
    unitPrice: 420,
    stockQuantity: 0,
    reorderLevel: 5,
    supplier: 'Chassis Brakes International',
    taxRate: 18,
    status: 'OUT_OF_STOCK',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
];

export const INITIAL_LABOUR_RATES: Labour[] = [
  { id: 'lab-1', code: 'LBR-ENG-OIL', description: 'Engine Oil & Filter Replacement Service', standardHours: 0.8, ratePerHour: 750 },
  { id: 'lab-2', code: 'LBR-BRK-FRT', description: 'Front Brake Pads Removal & Replacement', standardHours: 1.2, ratePerHour: 800 },
  { id: 'lab-3', code: 'LBR-BRK-BLEED', description: 'Hydraulic Brake System Bleeding & Fluid Flush', standardHours: 1.0, ratePerHour: 800 },
  { id: 'lab-4', code: 'LBR-WHL-ALIGN', description: '3D Computerized Wheel Alignment & Camber Calibration', standardHours: 1.0, ratePerHour: 850 },
  { id: 'lab-5', code: 'LBR-WHL-BAL', description: 'Dynamic Wheel Balancing (4 Wheels + Weights)', standardHours: 1.2, ratePerHour: 850 },
  { id: 'lab-6', code: 'LBR-AC-SRV', description: 'HVAC AC Servicing, Coil Cleaning & Gas Recharging', standardHours: 2.5, ratePerHour: 900 },
  { id: 'lab-7', code: 'LBR-GEN-INSP', description: 'Comprehensive 40-Point Safety & Mechanical Inspection', standardHours: 1.5, ratePerHour: 700 },
  { id: 'lab-8', code: 'LBR-SUSP-OVRHL', description: 'Front Strut & Suspension Bushing Overhaul', standardHours: 3.5, ratePerHour: 950 },
  { id: 'lab-9', code: 'LBR-BAT-DIAG', description: 'Battery Cranking & Alternator Charging Circuit Test', standardHours: 0.5, ratePerHour: 700 },
  { id: 'lab-10', code: 'LBR-CLT-RPLC', description: 'Clutch Assembly Removal, Flywheel Facing & Fitting', standardHours: 4.5, ratePerHour: 1000 },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-1',
    bookingNumber: 'BK-1001',
    customerId: 'cust-1',
    customerName: 'Rahul Patil',
    customerPhone: '+91 98201 12345',
    vehicleId: 'veh-1',
    vehicleRegistration: 'MH 12 AB 4587',
    vehicleModel: 'Tata Nexon XZ+ (O)',
    serviceType: 'PERIODIC_MAINTENANCE',
    preferredDate: '2026-09-24',
    preferredTime: '09:30',
    complaintDescription: 'Scheduled 35,000 km periodic service, front brake squealing sound, AC odor',
    pickupDropPreference: 'SELF_DROP',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    status: 'CHECKED_IN',
    createdAt: '2026-09-23T14:30:00Z',
    updatedAt: '2026-09-24T08:30:00Z',
  },
  {
    id: 'bk-2',
    bookingNumber: 'BK-1002',
    customerId: 'cust-2',
    customerName: 'Priya Sharma',
    customerPhone: '+91 98112 54321',
    vehicleId: 'veh-2',
    vehicleRegistration: 'DL 03 CC 9821',
    vehicleModel: 'Hyundai Creta SX (O)',
    serviceType: 'GENERAL_REPAIR',
    preferredDate: '2026-09-24',
    preferredTime: '10:00',
    complaintDescription: 'Engine vibration when idling at signals, slight left steering pull',
    pickupDropPreference: 'PICKUP_REQUESTED',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    status: 'CHECKED_IN',
    createdAt: '2026-09-23T16:00:00Z',
    updatedAt: '2026-09-24T09:00:00Z',
  },
  {
    id: 'bk-3',
    bookingNumber: 'BK-1003',
    customerId: 'cust-3',
    customerName: 'Amit Verma',
    customerPhone: '+91 98450 67890',
    vehicleId: 'veh-3',
    vehicleRegistration: 'KA 05 MN 3344',
    vehicleModel: 'Mahindra XUV700 AX7',
    serviceType: 'PERIODIC_MAINTENANCE',
    preferredDate: '2026-09-24',
    preferredTime: '11:00',
    complaintDescription: '20,000 km oil service, suspension thud over speed bumps, wiper streaking',
    pickupDropPreference: 'SELF_DROP',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    status: 'CHECKED_IN',
    createdAt: '2026-09-22T10:00:00Z',
    updatedAt: '2026-09-24T09:15:00Z',
  },
  {
    id: 'bk-4',
    bookingNumber: 'BK-1004',
    customerId: 'cust-4',
    customerName: 'Vikram Malhotra',
    customerPhone: '+91 98210 99887',
    vehicleId: 'veh-4',
    vehicleRegistration: 'MH 02 EF 1209',
    vehicleModel: 'Toyota Innova Hycross',
    serviceType: 'BRAKE_SERVICE',
    preferredDate: '2026-09-23',
    preferredTime: '14:00',
    complaintDescription: 'Brake pedal pulsating during highway deceleration, general check',
    pickupDropPreference: 'DOORSTEP_DROP',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    status: 'CHECKED_IN',
    createdAt: '2026-09-22T11:00:00Z',
    updatedAt: '2026-09-23T14:15:00Z',
  },
  {
    id: 'bk-5',
    bookingNumber: 'BK-1005',
    customerId: 'cust-5',
    customerName: 'Sunita Desai',
    customerPhone: '+91 98790 11223',
    vehicleId: 'veh-5',
    vehicleRegistration: 'GJ 01 KK 7712',
    vehicleModel: 'Maruti Suzuki Grand Vitara',
    serviceType: 'PERIODIC_MAINTENANCE',
    preferredDate: '2026-09-22',
    preferredTime: '09:00',
    complaintDescription: '40,000 km comprehensive service, oil replacement, wheel rotation',
    pickupDropPreference: 'SELF_DROP',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    status: 'COMPLETED',
    createdAt: '2026-09-21T09:00:00Z',
    updatedAt: '2026-09-23T17:00:00Z',
  },
  {
    id: 'bk-6',
    bookingNumber: 'BK-1006',
    customerId: 'cust-6',
    customerName: 'Rajesh Iyer',
    customerPhone: '+91 98401 44556',
    vehicleId: 'veh-6',
    vehicleRegistration: 'TN 07 AX 6543',
    vehicleModel: 'Kia Seltos GTX Plus',
    serviceType: 'AC_SERVICE',
    preferredDate: '2026-09-24',
    preferredTime: '14:30',
    complaintDescription: 'Cabin AC not cooling effectively in afternoon traffic, blower whistling',
    pickupDropPreference: 'SELF_DROP',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    status: 'CONFIRMED',
    createdAt: '2026-09-23T18:00:00Z',
    updatedAt: '2026-09-24T07:30:00Z',
  },
  {
    id: 'bk-7',
    bookingNumber: 'BK-1007',
    customerId: 'cust-7',
    customerName: 'Sneha Reddy',
    customerPhone: '+91 98850 77889',
    vehicleId: 'veh-7',
    vehicleRegistration: 'TS 09 CD 4321',
    vehicleModel: 'Honda City ZX',
    serviceType: 'BRAKE_SERVICE',
    preferredDate: '2026-09-24',
    preferredTime: '15:00',
    complaintDescription: 'Brake pedal requires heavy pressure, brake fluid level check',
    pickupDropPreference: 'PICKUP_REQUESTED',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    status: 'CONFIRMED',
    createdAt: '2026-09-23T19:30:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'bk-8',
    bookingNumber: 'BK-1008',
    customerId: 'cust-8',
    customerName: 'Arjun Nair',
    customerPhone: '+91 98470 33221',
    vehicleId: 'veh-8',
    vehicleRegistration: 'KL 07 BG 8899',
    vehicleModel: 'Tata Harrier Fearless Plus',
    serviceType: 'GENERAL_REPAIR',
    preferredDate: '2026-09-25',
    preferredTime: '10:00',
    complaintDescription: 'Rear parking sensors intermittent error on dashboard screen',
    pickupDropPreference: 'SELF_DROP',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    status: 'REQUESTED',
    createdAt: '2026-09-24T06:00:00Z',
    updatedAt: '2026-09-24T06:00:00Z',
  },
  {
    id: 'bk-9',
    bookingNumber: 'BK-1009',
    customerId: 'cust-9',
    customerName: 'Meera Joshi',
    customerPhone: '+91 98220 55667',
    vehicleId: 'veh-9',
    vehicleRegistration: 'MH 14 GH 5678',
    vehicleModel: 'Mahindra Thar LX 4x4',
    serviceType: 'PERIODIC_MAINTENANCE',
    preferredDate: '2026-09-25',
    preferredTime: '11:30',
    complaintDescription: 'Post monsoon underbody wash, differential fluid check, steering check',
    pickupDropPreference: 'SELF_DROP',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    status: 'REQUESTED',
    createdAt: '2026-09-24T07:15:00Z',
    updatedAt: '2026-09-24T07:15:00Z',
  },
  {
    id: 'bk-10',
    bookingNumber: 'BK-1010',
    customerId: 'cust-10',
    customerName: 'Rohan Gupta',
    customerPhone: '+91 98100 22334',
    vehicleId: 'veh-10',
    vehicleRegistration: 'HR 26 BX 9012',
    vehicleModel: 'Skoda Kushaq Style 1.5 TSI',
    serviceType: 'EXPRESS_SERVICE',
    preferredDate: '2026-09-26',
    preferredTime: '09:30',
    complaintDescription: 'Quick pre-highway travel inspection, tyre pressures, fluids top-up',
    pickupDropPreference: 'SELF_DROP',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    status: 'REQUESTED',
    createdAt: '2026-09-24T08:10:00Z',
    updatedAt: '2026-09-24T08:10:00Z',
  },
];

export const INITIAL_JOB_CARDS: JobCard[] = [
  // 1. WAITING_FOR_APPROVAL: Rahul Patil's Tata Nexon - Perfect for Customer Portal & Estimate Approval Demo!
  {
    id: 'job-1',
    jobId: 'JOB-1001',
    bookingId: 'bk-1',
    customerId: 'cust-1',
    customerName: 'Rahul Patil',
    customerPhone: '+91 98201 12345',
    customerEmail: 'customer@autocare360.demo',
    vehicleId: 'veh-1',
    vehicleRegistration: 'MH 12 AB 4587',
    vehicleMake: 'Tata',
    vehicleModel: 'Nexon XZ+ (O)',
    vehicleYear: 2022,
    vehicleFuel: 'DIESEL',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    assignedTechnicianId: 'user-technician',
    assignedTechnicianName: 'Deepak Shinde',
    customerComplaint: 'Scheduled 35,000 km periodic service, front brake squealing sound, AC odor',
    currentOdometer: 34500,
    fuelLevelPercent: 65,
    status: 'WAITING_FOR_APPROVAL',
    overallProgressPercent: 25,
    createdAt: '2026-09-24T08:30:00Z',
    updatedAt: '2026-09-24T09:15:00Z',
    inspection: {
      id: 'insp-1',
      jobCardId: 'job-1',
      inspectorId: 'user-technician',
      inspectorName: 'Deepak Shinde',
      odometer: 34500,
      fuelLevelPercent: 65,
      visibleDamageNotes: 'Minor hairline scratch on rear bumper RHS corner; no dent',
      exteriorItems: [
        { id: 'ei-1', category: 'Exterior', item: 'Body condition & paint', condition: 'GOOD', notes: 'Rear bumper hairline scratch noted' },
        { id: 'ei-2', category: 'Exterior', item: 'Windshield & Glass', condition: 'GOOD', notes: 'Clear, no chips' },
        { id: 'ei-3', category: 'Exterior', item: 'Exterior Headlights & Taillights', condition: 'GOOD', notes: 'All functioning' },
        { id: 'ei-4', category: 'Exterior', item: 'Tyres & Tread Depth', condition: 'GOOD', notes: '5.2mm average tread remaining' },
        { id: 'ei-5', category: 'Exterior', item: 'Side Mirrors & Indicators', condition: 'GOOD', notes: 'Motor fold tested OK' },
        { id: 'ei-6', category: 'Exterior', item: 'Wipers & Washers', condition: 'ATTENTION', notes: 'Front wiper blades leaving light haze' },
      ],
      interiorItems: [
        { id: 'ii-1', category: 'Interior', item: 'Seats & Seatbelts', condition: 'GOOD', notes: 'Locks working properly' },
        { id: 'ii-2', category: 'Interior', item: 'Dashboard & Instrument Cluster', condition: 'GOOD', notes: 'No warning lights' },
        { id: 'ii-3', category: 'Interior', item: 'AC Cooling & Blower', condition: 'ATTENTION', notes: 'Mild foul odor, cabin filter clogged' },
        { id: 'ii-4', category: 'Interior', item: 'Audio & Infotainment', condition: 'GOOD', notes: 'Touchscreen responsive' },
        { id: 'ii-5', category: 'Interior', item: 'Power Windows & Central Locking', condition: 'GOOD', notes: 'Smooth operation' },
      ],
      engineItems: [
        { id: 'en-1', category: 'Engine', item: 'Engine Oil Level & Quality', condition: 'ATTENTION', notes: 'Oil dark, viscosity degraded, due for flush' },
        { id: 'en-2', category: 'Engine', item: 'Coolant Level & Concentration', condition: 'GOOD', notes: 'Level at MAX mark' },
        { id: 'en-3', category: 'Engine', item: 'Battery Voltage & Terminals', condition: 'GOOD', notes: '12.6V resting, clean terminals' },
        { id: 'en-4', category: 'Engine', item: 'Drive Belts & Pulleys', condition: 'GOOD', notes: 'No cracking observed' },
        { id: 'en-5', category: 'Engine', item: 'Air Filter Element', condition: 'ATTENTION', notes: 'Dust buildup, needs replacement' },
      ],
      safetyItems: [
        { id: 'si-1', category: 'Safety', item: 'Front Brake Pads Condition', condition: 'CRITICAL', notes: 'Pad thickness under 2.5mm, metal squeal warning clip contacting disc' },
        { id: 'si-2', category: 'Safety', item: 'Rear Brake Condition', condition: 'GOOD', notes: 'Lining thickness satisfactory at 4.5mm' },
        { id: 'si-3', category: 'Safety', item: 'Suspension Bushings & Struts', condition: 'GOOD', notes: 'No leaks or excessive play' },
        { id: 'si-4', category: 'Safety', item: 'Steering Rack & Tie Rods', condition: 'GOOD', notes: 'Centering accurate' },
      ],
      overallRemarks: 'Engine oil service and front brake pad replacement urgent for vehicle road safety.',
      completedAt: '2026-09-24T09:00:00Z',
    },
    tasks: [
      { id: 'tsk-1', jobCardId: 'job-1', description: 'Engine oil drain, flush, and filter replacement', estimatedLabourHours: 0.8, actualLabourHours: 0, status: 'PENDING', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde' },
      { id: 'tsk-2', jobCardId: 'job-1', description: 'Front brake caliper service & ceramic brake pads replacement', estimatedLabourHours: 1.2, actualLabourHours: 0, status: 'PENDING', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde' },
      { id: 'tsk-3', jobCardId: 'job-1', description: 'Air filter & Valeo cabin AC filter replacement with disinfectant', estimatedLabourHours: 0.6, actualLabourHours: 0, status: 'PENDING', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde' },
      { id: 'tsk-4', jobCardId: 'job-1', description: '3D Computerized 4-wheel alignment & tyre pressure calibration', estimatedLabourHours: 1.0, actualLabourHours: 0, status: 'PENDING', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde' },
    ],
    parts: [
      { id: 'jp-1', jobCardId: 'job-1', partId: 'part-1', partNumber: 'OIL-SYN-5W30', name: 'Castrol Edge Fully Synthetic 5W-30 (3.5L)', quantity: 1, unitPrice: 2450, taxRate: 18, taxAmount: 441, total: 2891 },
      { id: 'jp-2', jobCardId: 'job-1', partId: 'part-2', partNumber: 'FLT-OIL-BSH', name: 'Bosch High Efficiency Spin-On Oil Filter', quantity: 1, unitPrice: 380, taxRate: 18, taxAmount: 68.4, total: 448.4 },
      { id: 'jp-3', jobCardId: 'job-1', partId: 'part-5', partNumber: 'BRK-PAD-FRT', name: 'Brembo Low-Metallic Front Brake Pads Set', quantity: 1, unitPrice: 2800, taxRate: 18, taxAmount: 504, total: 3304 },
      { id: 'jp-4', jobCardId: 'job-1', partId: 'part-4', partNumber: 'FLT-AC-VAL', name: 'Valeo Activated Carbon Cabin AC Filter', quantity: 1, unitPrice: 650, taxRate: 18, taxAmount: 117, total: 767 },
    ],
    labour: [
      { id: 'jl-1', jobCardId: 'job-1', labourCode: 'LBR-ENG-OIL', description: 'Engine Oil & Filter Replacement Service', technicianId: 'user-technician', technicianName: 'Deepak Shinde', hours: 0.8, ratePerHour: 750, total: 600 },
      { id: 'jl-2', jobCardId: 'job-1', labourCode: 'LBR-BRK-FRT', description: 'Front Brake Pads Removal & Replacement', technicianId: 'user-technician', technicianName: 'Deepak Shinde', hours: 1.2, ratePerHour: 800, total: 960 },
      { id: 'jl-3', jobCardId: 'job-1', labourCode: 'LBR-WHL-ALIGN', description: '3D Computerized Wheel Alignment', technicianId: 'user-technician', technicianName: 'Deepak Shinde', hours: 1.0, ratePerHour: 850, total: 850 },
    ],
    estimate: {
      id: 'est-1',
      estimateNumber: 'EST-1001',
      jobCardId: 'job-1',
      partsSubtotal: 6280,
      labourSubtotal: 2410,
      additionalCharges: 250, // Consumables & sanitization
      discountAmount: 400, // Loyalty discount
      taxAmount: 1537.2,
      grandTotal: 10077.2,
      status: 'PENDING_APPROVAL',
      createdAt: '2026-09-24T09:15:00Z',
      updatedAt: '2026-09-24T09:15:00Z',
    },
  },

  // 2. IN_PROGRESS: Priya Sharma's Creta - 60% completed
  {
    id: 'job-2',
    jobId: 'JOB-1002',
    bookingId: 'bk-2',
    customerId: 'cust-2',
    customerName: 'Priya Sharma',
    customerPhone: '+91 98112 54321',
    customerEmail: 'priya.sharma@example.in',
    vehicleId: 'veh-2',
    vehicleRegistration: 'DL 03 CC 9821',
    vehicleMake: 'Hyundai',
    vehicleModel: 'Creta SX (O)',
    vehicleYear: 2021,
    vehicleFuel: 'PETROL',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    assignedTechnicianId: 'user-technician',
    assignedTechnicianName: 'Deepak Shinde',
    customerComplaint: 'Engine vibration when idling at signals, slight left steering pull',
    currentOdometer: 42100,
    fuelLevelPercent: 45,
    status: 'IN_PROGRESS',
    overallProgressPercent: 67,
    createdAt: '2026-09-24T07:45:00Z',
    updatedAt: '2026-09-24T10:30:00Z',
    tasks: [
      { id: 'tsk-21', jobCardId: 'job-2', description: 'Spark plugs inspection and replacement with NGK Laser Iridium', estimatedLabourHours: 0.8, actualLabourHours: 0.7, status: 'COMPLETED', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde', completedAt: '2026-09-24T09:30:00Z' },
      { id: 'tsk-22', jobCardId: 'job-2', description: 'Throttle body cleaning & electronic calibration', estimatedLabourHours: 1.0, actualLabourHours: 1.1, status: 'COMPLETED', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde', completedAt: '2026-09-24T10:15:00Z' },
      { id: 'tsk-23', jobCardId: 'job-2', description: '3D Wheel alignment & tie rod end adjustment', estimatedLabourHours: 1.2, actualLabourHours: 0, status: 'IN_PROGRESS', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde', startedAt: '2026-09-24T10:20:00Z' },
    ],
    parts: [
      { id: 'jp-21', jobCardId: 'job-2', partId: 'part-10', partNumber: 'SPK-NGK-IR4', name: 'NGK Laser Iridium Spark Plugs (Pack of 4)', quantity: 1, unitPrice: 1950, taxRate: 18, taxAmount: 351, total: 2301 },
      { id: 'jp-22', jobCardId: 'job-2', partId: 'part-3', partNumber: 'FLT-AIR-PUR', name: 'Purolator Engine Air Filter Element', quantity: 1, unitPrice: 520, taxRate: 18, taxAmount: 93.6, total: 613.6 },
    ],
    labour: [
      { id: 'jl-21', jobCardId: 'job-2', labourCode: 'LBR-GEN-INSP', description: 'Throttle Body & Electronic Diagnosis', technicianId: 'user-technician', technicianName: 'Deepak Shinde', hours: 1.5, ratePerHour: 700, total: 1050 },
      { id: 'jl-22', jobCardId: 'job-2', labourCode: 'LBR-WHL-ALIGN', description: '3D Computerized Wheel Alignment', technicianId: 'user-technician', technicianName: 'Deepak Shinde', hours: 1.0, ratePerHour: 850, total: 850 },
    ],
    estimate: {
      id: 'est-2',
      estimateNumber: 'EST-1002',
      jobCardId: 'job-2',
      partsSubtotal: 2470,
      labourSubtotal: 1900,
      additionalCharges: 150,
      discountAmount: 200,
      taxAmount: 777.6,
      grandTotal: 5097.6,
      status: 'APPROVED',
      approvedByCustomerAt: '2026-09-24T08:15:00Z',
      createdAt: '2026-09-24T08:00:00Z',
      updatedAt: '2026-09-24T08:15:00Z',
    },
  },

  // 3. QUALITY_CHECK: Amit Verma's XUV700 - Tasks completed, ready for QA manager
  {
    id: 'job-3',
    jobId: 'JOB-1003',
    bookingId: 'bk-3',
    customerId: 'cust-3',
    customerName: 'Amit Verma',
    customerPhone: '+91 98450 67890',
    customerEmail: 'amit.verma@example.in',
    vehicleId: 'veh-3',
    vehicleRegistration: 'KA 05 MN 3344',
    vehicleMake: 'Mahindra',
    vehicleModel: 'XUV700 AX7',
    vehicleYear: 2023,
    vehicleFuel: 'DIESEL',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    assignedTechnicianId: 'user-technician',
    assignedTechnicianName: 'Deepak Shinde',
    customerComplaint: '20,000 km oil service, suspension thud over speed bumps, wiper streaking',
    currentOdometer: 21800,
    fuelLevelPercent: 50,
    status: 'QUALITY_CHECK',
    overallProgressPercent: 100,
    createdAt: '2026-09-23T11:00:00Z',
    updatedAt: '2026-09-24T09:45:00Z',
    tasks: [
      { id: 'tsk-31', jobCardId: 'job-3', description: 'Engine oil flush & Castrol 5W-30 synthetic refilling', estimatedLabourHours: 0.8, actualLabourHours: 0.8, status: 'COMPLETED', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde', completedAt: '2026-09-24T08:30:00Z' },
      { id: 'tsk-32', jobCardId: 'job-3', description: 'Front stabilizer bar bush replacement & suspension torque check', estimatedLabourHours: 2.0, actualLabourHours: 2.2, status: 'COMPLETED', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde', completedAt: '2026-09-24T09:20:00Z' },
      { id: 'tsk-33', jobCardId: 'job-3', description: 'Bosch Aerotwin frameless wipers pair installation', estimatedLabourHours: 0.3, actualLabourHours: 0.2, status: 'COMPLETED', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde', completedAt: '2026-09-24T09:40:00Z' },
    ],
    parts: [
      { id: 'jp-31', jobCardId: 'job-3', partId: 'part-1', partNumber: 'OIL-SYN-5W30', name: 'Castrol Edge Fully Synthetic 5W-30 (3.5L)', quantity: 1, unitPrice: 2450, taxRate: 18, taxAmount: 441, total: 2891 },
      { id: 'jp-32', jobCardId: 'job-3', partId: 'part-2', partNumber: 'FLT-OIL-BSH', name: 'Bosch High Efficiency Spin-On Oil Filter', quantity: 1, unitPrice: 380, taxRate: 18, taxAmount: 68.4, total: 448.4 },
      { id: 'jp-33', jobCardId: 'job-3', partId: 'part-15', partNumber: 'SUS-BSH-MNR', name: 'Monroe Heavy-Duty Front Suspension Bush Kit', quantity: 1, unitPrice: 1850, taxRate: 18, taxAmount: 333, total: 2183 },
      { id: 'jp-34', jobCardId: 'job-3', partId: 'part-12', partNumber: 'WIP-BSH-AERO', name: 'Bosch Clear Advantage Frameless Wipers', quantity: 1, unitPrice: 1150, taxRate: 18, taxAmount: 207, total: 1357 },
    ],
    labour: [
      { id: 'jl-31', jobCardId: 'job-3', labourCode: 'LBR-ENG-OIL', description: 'Engine Oil & Filter Service', technicianId: 'user-technician', technicianName: 'Deepak Shinde', hours: 0.8, ratePerHour: 750, total: 600 },
      { id: 'jl-32', jobCardId: 'job-3', labourCode: 'LBR-SUSP-OVRHL', description: 'Suspension Bushing Replacement', technicianId: 'user-technician', technicianName: 'Deepak Shinde', hours: 2.0, ratePerHour: 950, total: 1900 },
    ],
    estimate: {
      id: 'est-3',
      estimateNumber: 'EST-1003',
      jobCardId: 'job-3',
      partsSubtotal: 5830,
      labourSubtotal: 2500,
      additionalCharges: 200,
      discountAmount: 350,
      taxAmount: 1472.4,
      grandTotal: 9652.4,
      status: 'APPROVED',
      approvedByCustomerAt: '2026-09-23T15:00:00Z',
      createdAt: '2026-09-23T14:00:00Z',
      updatedAt: '2026-09-23T15:00:00Z',
    },
  },

  // 4. READY_FOR_DELIVERY: Vikram Malhotra's Innova Hycross - QC passed, invoice generated, awaiting billing & delivery
  {
    id: 'job-4',
    jobId: 'JOB-1004',
    bookingId: 'bk-4',
    customerId: 'cust-4',
    customerName: 'Vikram Malhotra',
    customerPhone: '+91 98210 99887',
    customerEmail: 'vikram.malhotra@example.in',
    vehicleId: 'veh-4',
    vehicleRegistration: 'MH 02 EF 1209',
    vehicleMake: 'Toyota',
    vehicleModel: 'Innova Hycross',
    vehicleYear: 2023,
    vehicleFuel: 'HYBRID',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    assignedTechnicianId: 'user-technician',
    assignedTechnicianName: 'Deepak Shinde',
    customerComplaint: 'Brake pedal pulsating during highway deceleration, general check',
    currentOdometer: 28400,
    fuelLevelPercent: 70,
    status: 'READY_FOR_DELIVERY',
    overallProgressPercent: 100,
    invoiceId: 'inv-4',
    invoiceNumber: 'INV-1004',
    createdAt: '2026-09-23T14:30:00Z',
    updatedAt: '2026-09-24T08:15:00Z',
    tasks: [
      { id: 'tsk-41', jobCardId: 'job-4', description: 'Front ventilated brake disc rotor replacement and caliper grease', estimatedLabourHours: 1.5, actualLabourHours: 1.4, status: 'COMPLETED', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde', completedAt: '2026-09-23T17:00:00Z' },
      { id: 'tsk-42', jobCardId: 'job-4', description: 'DOT 4 brake hydraulic system flushing & high pressure bleeding', estimatedLabourHours: 1.0, actualLabourHours: 0.9, status: 'COMPLETED', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde', completedAt: '2026-09-23T18:00:00Z' },
      { id: 'tsk-43', jobCardId: 'job-4', description: 'Road test 10 km speed deceleration verification', estimatedLabourHours: 0.5, actualLabourHours: 0.5, status: 'COMPLETED', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde', completedAt: '2026-09-24T07:30:00Z' },
    ],
    parts: [
      { id: 'jp-41', jobCardId: 'job-4', partId: 'part-7', partNumber: 'BRK-DISC-280', name: 'Front Ventilated Brake Rotor Disc Pair', quantity: 1, unitPrice: 4200, taxRate: 18, taxAmount: 756, total: 4956 },
      { id: 'jp-42', jobCardId: 'job-4', partId: 'part-5', partNumber: 'BRK-PAD-FRT', name: 'Brembo Front Brake Pads Set', quantity: 1, unitPrice: 2800, taxRate: 18, taxAmount: 504, total: 3304 },
      { id: 'jp-43', jobCardId: 'job-4', partId: 'part-8', partNumber: 'FLD-DOT4-500', name: 'Castrol Response Super DOT 4 Brake Fluid', quantity: 2, unitPrice: 340, taxRate: 18, taxAmount: 122.4, total: 802.4 },
    ],
    labour: [
      { id: 'jl-41', jobCardId: 'job-4', labourCode: 'LBR-BRK-FRT', description: 'Brake Disc & Pad Fitting', technicianId: 'user-technician', technicianName: 'Deepak Shinde', hours: 1.5, ratePerHour: 800, total: 1200 },
      { id: 'jl-42', jobCardId: 'job-4', labourCode: 'LBR-BRK-BLEED', description: 'Brake Bleeding & Fluid Flush', technicianId: 'user-technician', technicianName: 'Deepak Shinde', hours: 1.0, ratePerHour: 800, total: 800 },
    ],
    qualityCheck: {
      id: 'qc-4',
      jobCardId: 'job-4',
      inspectorId: 'user-manager',
      inspectorName: 'Arvind Swamy',
      items: [
        { id: 'qci-1', title: 'Service execution completed', description: 'All assigned tasks marked complete with notes', passed: true },
        { id: 'qci-2', title: 'OEM Parts properly torqued', description: 'Brake disc bolts & caliper guide pins torqued to spec', passed: true },
        { id: 'qci-3', title: 'Vehicle foam wash & vacuum', description: 'Interior cleaned, glass streak-free, wheels polished', passed: true },
        { id: 'qci-4', title: 'OBD Diagnostics & Warning Lights', description: 'ABS / ESC ECU scan clear of DTCs', passed: true },
        { id: 'qci-5', title: 'Dynamic Road Test', description: 'Pedal vibration eliminated, bite responsive', passed: true },
        { id: 'qci-6', title: 'Customer complaint resolved', description: 'Original vibration issue rectified', passed: true },
      ],
      status: 'PASSED',
      remarks: 'All quality checklist items passed with excellent brake response.',
      checkedAt: '2026-09-24T08:00:00Z',
    },
  },

  // 5. DELIVERED: Sunita Desai's Grand Vitara - Completed full cycle
  {
    id: 'job-5',
    jobId: 'JOB-1005',
    bookingId: 'bk-5',
    customerId: 'cust-5',
    customerName: 'Sunita Desai',
    customerPhone: '+91 98790 11223',
    customerEmail: 'sunita.desai@example.in',
    vehicleId: 'veh-5',
    vehicleRegistration: 'GJ 01 KK 7712',
    vehicleMake: 'Maruti Suzuki',
    vehicleModel: 'Grand Vitara',
    vehicleYear: 2022,
    vehicleFuel: 'PETROL',
    assignedAdvisorId: 'user-advisor',
    assignedAdvisorName: 'Sameer Joshi',
    assignedTechnicianId: 'user-technician',
    assignedTechnicianName: 'Deepak Shinde',
    customerComplaint: '40,000 km comprehensive service, oil replacement, wheel rotation',
    currentOdometer: 38900,
    fuelLevelPercent: 80,
    status: 'DELIVERED',
    overallProgressPercent: 100,
    invoiceId: 'inv-5',
    invoiceNumber: 'INV-1005',
    delivery: {
      id: 'del-5',
      jobCardId: 'job-5',
      vehicleId: 'veh-5',
      customerId: 'cust-5',
      deliveryDate: '2026-09-23T17:30:00Z',
      finalOdometer: 38912,
      customerConfirmation: true,
      staffMemberId: 'user-advisor',
      staffMemberName: 'Sameer Joshi',
      deliveryNotes: 'Vehicle delivered in clean condition. Customer satisfied with prompt turnaround.',
      createdAt: '2026-09-23T17:30:00Z',
    },
    createdAt: '2026-09-22T09:30:00Z',
    updatedAt: '2026-09-23T17:30:00Z',
    tasks: [
      { id: 'tsk-51', jobCardId: 'job-5', description: 'Periodic lubrication service', estimatedLabourHours: 1.0, actualLabourHours: 0.9, status: 'COMPLETED', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde', completedAt: '2026-09-23T12:00:00Z' },
      { id: 'tsk-52', jobCardId: 'job-5', description: '4-Wheel balancing & tyre rotation', estimatedLabourHours: 1.2, actualLabourHours: 1.2, status: 'COMPLETED', assignedTechnicianId: 'user-technician', assignedTechnicianName: 'Deepak Shinde', completedAt: '2026-09-23T14:30:00Z' },
    ],
    parts: [
      { id: 'jp-51', jobCardId: 'job-5', partId: 'part-1', partNumber: 'OIL-SYN-5W30', name: 'Castrol Edge Fully Synthetic 5W-30', quantity: 1, unitPrice: 2450, taxRate: 18, taxAmount: 441, total: 2891 },
      { id: 'jp-52', jobCardId: 'job-5', partId: 'part-2', partNumber: 'FLT-OIL-BSH', name: 'Bosch High Efficiency Spin-On Oil Filter', quantity: 1, unitPrice: 380, taxRate: 18, taxAmount: 68.4, total: 448.4 },
    ],
    labour: [
      { id: 'jl-51', jobCardId: 'job-5', labourCode: 'LBR-ENG-OIL', description: 'Engine Oil & Filter Service', technicianId: 'user-technician', technicianName: 'Deepak Shinde', hours: 0.8, ratePerHour: 750, total: 600 },
      { id: 'jl-52', jobCardId: 'job-5', labourCode: 'LBR-WHL-BAL', description: '4-Wheel Balancing', technicianId: 'user-technician', technicianName: 'Deepak Shinde', hours: 1.2, ratePerHour: 850, total: 1020 },
    ],
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-4',
    invoiceNumber: 'INV-1004',
    invoiceDate: '2026-09-24T08:15:00Z',
    jobCardId: 'job-4',
    customerId: 'cust-4',
    customerName: 'Vikram Malhotra',
    customerPhone: '+91 98210 99887',
    customerEmail: 'vikram.malhotra@example.in',
    customerAddress: '14A, Silver Beach Estate, Juhu, Mumbai, MH',
    vehicleId: 'veh-4',
    vehicleRegistration: 'MH 02 EF 1209',
    vehicleModel: 'Toyota Innova Hycross Hybrid',
    partsSubtotal: 7680,
    labourSubtotal: 2000,
    additionalCharges: 250,
    discountAmount: 500,
    taxAmount: 1742.4,
    grandTotal: 11172.4,
    paidAmount: 0,
    balanceAmount: 11172.4,
    paymentStatus: 'UNPAID',
    payments: [],
    createdAt: '2026-09-24T08:15:00Z',
    updatedAt: '2026-09-24T08:15:00Z',
  },
  {
    id: 'inv-5',
    invoiceNumber: 'INV-1005',
    invoiceDate: '2026-09-23T16:00:00Z',
    jobCardId: 'job-5',
    customerId: 'cust-5',
    customerName: 'Sunita Desai',
    customerPhone: '+91 98790 11223',
    customerEmail: 'sunita.desai@example.in',
    customerAddress: 'Plot 88, Bodakdev, Ahmedabad, GJ',
    vehicleId: 'veh-5',
    vehicleRegistration: 'GJ 01 KK 7712',
    vehicleModel: 'Maruti Suzuki Grand Vitara',
    partsSubtotal: 2830,
    labourSubtotal: 1620,
    additionalCharges: 150,
    discountAmount: 200,
    taxAmount: 801,
    grandTotal: 5201,
    paidAmount: 5201,
    balanceAmount: 0,
    paymentStatus: 'PAID',
    payments: [
      {
        id: 'pay-501',
        paymentNumber: 'PAY-1005',
        invoiceId: 'inv-5',
        amount: 5201,
        paymentMethod: 'UPI',
        referenceNumber: 'UPI/626789123490/HDFC',
        notes: 'GPay payment confirmed via QR code',
        receivedById: 'user-billing',
        receivedByName: 'Neha Kulkarni',
        paidAt: '2026-09-23T16:30:00Z',
      },
    ],
    createdAt: '2026-09-23T16:00:00Z',
    updatedAt: '2026-09-23T16:30:00Z',
  },
];

export const INITIAL_SERVICE_HISTORY: ServiceHistoryItem[] = [
  {
    id: 'sh-1',
    vehicleId: 'veh-1',
    jobCardId: 'job-hist-1',
    date: '2026-03-15',
    odometer: 25000,
    complaints: '25,000 km regular service, AC cooling check',
    servicesPerformed: ['Engine oil change', 'Oil filter change', 'AC disinfectant service', 'Brake pads inspection'],
    partsUsed: ['Castrol Edge 5W-30', 'Bosch Oil Filter', 'Cabin Air Filter'],
    totalAmount: 6850,
    technicianName: 'Deepak Shinde',
    serviceAdvisorName: 'Sameer Joshi',
    invoiceNumber: 'INV-0912',
    status: 'DELIVERED',
  },
  {
    id: 'sh-2',
    vehicleId: 'veh-1',
    jobCardId: 'job-hist-2',
    date: '2025-09-10',
    odometer: 15000,
    complaints: '15,000 km periodic service, wheel alignment',
    servicesPerformed: ['Engine oil change', 'Wheel alignment', 'Tyre balancing', 'Coolant top-up'],
    partsUsed: ['Engine Oil 5W-30', 'Oil Filter'],
    totalAmount: 4920,
    technicianName: 'Deepak Shinde',
    serviceAdvisorName: 'Sameer Joshi',
    invoiceNumber: 'INV-0780',
    status: 'DELIVERED',
  },
  {
    id: 'sh-3',
    vehicleId: 'veh-5',
    jobCardId: 'job-5',
    date: '2026-09-23',
    odometer: 38900,
    complaints: '40,000 km comprehensive service, oil replacement, wheel rotation',
    servicesPerformed: ['Periodic lubrication service', '4-Wheel balancing & tyre rotation'],
    partsUsed: ['Castrol Edge Fully Synthetic 5W-30', 'Bosch Oil Filter'],
    totalAmount: 5201,
    technicianName: 'Deepak Shinde',
    serviceAdvisorName: 'Sameer Joshi',
    invoiceNumber: 'INV-1005',
    status: 'DELIVERED',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    title: 'Estimate Awaiting Approval',
    message: 'Estimate #EST-1001 for Rahul Patil (MH 12 AB 4587) is waiting for customer approval.',
    type: 'warning',
    isRead: false,
    link: '/jobs/job-1',
    roleTarget: 'ALL',
    createdAt: '2026-09-24T09:15:00Z',
  },
  {
    id: 'notif-2',
    title: 'Quality Check Required',
    message: 'Job #JOB-1003 for Amit Verma (KA 05 MN 3344) is ready for manager quality check.',
    type: 'info',
    isRead: false,
    link: '/jobs/job-3',
    roleTarget: 'SERVICE_MANAGER',
    createdAt: '2026-09-24T09:45:00Z',
  },
  {
    id: 'notif-3',
    title: 'Low Stock Alert',
    message: 'Part "Brembo Front Brake Pads Set" (BP-PAD-FRT) has reached low stock level (3 left).',
    type: 'urgent',
    isRead: false,
    link: '/inventory',
    roleTarget: 'ADMIN',
    createdAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'notif-4',
    title: 'Vehicle Ready for Delivery',
    message: 'Toyota Innova Hycross (MH 02 EF 1209) has passed QA and is ready for payment & delivery handover.',
    type: 'success',
    isRead: false,
    link: '/billing',
    roleTarget: 'BILLING_STAFF',
    createdAt: '2026-09-24T08:15:00Z',
  },
  {
    id: 'notif-5',
    title: 'Payment Received',
    message: 'Payment of ₹5,201 received via UPI for Invoice #INV-1005 (Sunita Desai).',
    type: 'success',
    isRead: true,
    link: '/billing',
    roleTarget: 'BILLING_STAFF',
    createdAt: '2026-09-23T16:35:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    timestamp: '2026-09-24T09:15:00Z',
    userId: 'user-advisor',
    userName: 'Sameer Joshi',
    userRole: 'SERVICE_ADVISOR',
    action: 'ESTIMATE_CREATED',
    entity: 'Estimate',
    entityId: 'EST-1001',
    description: 'Generated estimate of ₹10,077.20 for Job Card #JOB-1001 (Rahul Patil)',
  },
  {
    id: 'aud-2',
    timestamp: '2026-09-24T09:00:00Z',
    userId: 'user-technician',
    userName: 'Deepak Shinde',
    userRole: 'TECHNICIAN',
    action: 'INSPECTION_COMPLETED',
    entity: 'Inspection',
    entityId: 'insp-1',
    description: 'Completed 20-point digital vehicle checklist for MH 12 AB 4587',
  },
  {
    id: 'aud-3',
    timestamp: '2026-09-24T08:30:00Z',
    userId: 'user-advisor',
    userName: 'Sameer Joshi',
    userRole: 'SERVICE_ADVISOR',
    action: 'VEHICLE_CHECKED_IN',
    entity: 'JobCard',
    entityId: 'JOB-1001',
    description: 'Checked in vehicle MH 12 AB 4587 at 34,500 km and created Job Card',
  },
  {
    id: 'aud-4',
    timestamp: '2026-09-24T08:15:00Z',
    userId: 'user-billing',
    userName: 'Neha Kulkarni',
    userRole: 'BILLING_STAFF',
    action: 'INVOICE_GENERATED',
    entity: 'Invoice',
    entityId: 'INV-1004',
    description: 'Generated final tax invoice #INV-1004 for ₹11,172.40 for Vikram Malhotra',
  },
  {
    id: 'aud-5',
    timestamp: '2026-09-24T08:00:00Z',
    userId: 'user-manager',
    userName: 'Arvind Swamy',
    userRole: 'SERVICE_MANAGER',
    action: 'QUALITY_CHECK_PASSED',
    entity: 'QualityCheck',
    entityId: 'qc-4',
    description: 'Passed 6-point Quality Inspection for Job #JOB-1004 (MH 02 EF 1209)',
  },
  {
    id: 'aud-6',
    timestamp: '2026-09-23T17:30:00Z',
    userId: 'user-advisor',
    userName: 'Sameer Joshi',
    userRole: 'SERVICE_ADVISOR',
    action: 'VEHICLE_DELIVERED',
    entity: 'Delivery',
    entityId: 'del-5',
    description: 'Delivered vehicle GJ 01 KK 7712 to customer Sunita Desai after payment clearance',
  },
];
